version: "3.2"

networks:
  interna: {}

services:
  www:
    image: tuxed/php:8.0.1
    env_file: .env
    volumes:
      - ./BlackStone/:/var/www/html/
      - ./conf/php.ini:/usr/local/etc/php/php.ini
      - ./conf/conexion.php:/var/www/html/conexion.php:rw
    depends_on:
      - db
    networks:
      - interna
    ports:
      - '80:80'

  db:
    image: mysql:5.7
    env_file: .env
    volumes:
      - ./BBDD/blackstone.sql:/docker-entrypoint-initdb.d/blackstone.sql
      - ./docker-volumes/mysql/data:/var/lib/mysql
    networks:
      - interna

